version: "3.9"
services:
  web:
    image: self-nginx
    volumes:
      - "./config/nginx/templates:/etc/nginx/templates"
      - "./../vhost:/var/www/"
      - "./config/ssl:/etc/ssl"
    ports:
      - "8080:80"
      - "3443:443"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80 
    depends_on:
      - mariadb 
      - php   
      # - memcached
      - redis 
  php:
    image: self-php8.0
    volumes:
      - "./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini"   
      - "./../vhost:/var/www/"
  # mysqldb:
  #       image: mysql:${MYSQL_VERSION}
  #       container_name: ${MYSQL_HOST}
  #       restart: always
  #       env_file:
  #           - ".env"
  #       environment:
  #           - MYSQL_DATABASE=${MYSQL_DATABASE}
  #           - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #           - MYSQL_USER=${MYSQL_USER}
  #           - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #       ports:
  #           - "8989:3306"
  #       volumes:
  #           - "./config/mysql/data/db/mysql:/var/lib/mysql" 
  mariadb:
        image: mariadb:latest
        container_name: ${MARIADB_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MARIADB_DATABASE=${MYSQL_DATABASE}
            - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MARIADB_USER=${MYSQL_USER}
            - MARIADB_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./config/mariadb/data/db/:/var/lib/mysql"           
  myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8000:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        depends_on:
            - mariadb
  # memcached:
  #       image: memcached:latest
  #       container_name: memcached
  #       command:
  #         - '-m 30'
  #       ports:
  #         - '22122:11211'
  redis:
        image: redis:latest
        container_name: redis
        volumes:
          - "./config/redis/redis.conf:/usr/local/etc/redis/redis.conf"  
        ports:
          - '6378:6379'                               